[package]
name = "editor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
dioxus = { version = "0.7" }
clap = "4.6"
tokio = { version = "1", features = ["full"] }
text-size = "1.1.1"
serde = { version = "1.0", features = ["derive"] }
toml = "1.1.6+spec-1.1.0"
thiserror = "2"
enum_dispatch = "0.3"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
